### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by fdeswardt** [salabim/ycecream#1]
Getting **TypeError: 'NoneType' object is not subscriptable** when using the example usage on README:

```
from ycecream import y

def add2(i):
    return i + 2

y(add2(1000))
```

Full error message is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mylocaluser/test-ycecream/venv/lib/python3.8/site-packages/ycecream/ycecream.py", line 220, in __call__
    this_line = frame.code_context[0].strip()
TypeError: 'NoneType' object is not subscriptable
```

Using new isolated venv with the following packages and their versions:
```
Package    Version
---------- -------
pip        21.0.1
setuptools 49.2.1
ycecream   1.1.4
```

**Comment by salabim** [comment]
Strange.
When I run it, everything seems to be fine.

Can you tell me how you run this code?
What operating system, what IDE (if any), etc.

**Comment by fdeswardt** [comment]
I'm on OSX with detailed OS ver as follows:
```
 uname -na
Darwin MYMAC 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```
and here are the complete steps from creation of venv to the error: 
```
cd ~
mkdir test-ycecream
cd test-ycecream
python3 -m venv venv
source venv/bin/activate
pip install pip --upgrade
pip install ycecream
python
```

and then I enter the sample code by copy/paste from README page:
```
from ycecream import y

def add2(i):
    return i + 2

y(add2(1000))
```

**Comment by salabim** [comment]
Are you running this in a REPL?
If so, that is not supported. The error message should be cleared, though. I will fix that in the next release.

If you are running this from a .py file, I have to look at it.

**Comment by fdeswardt** [comment]
Yip, using this in the standard Python REPL and you are correct, when I put the sample in a test-y.py file and run it with "python test-y" then it works.

Recommend you add a disclaimer that ycecream is only supported in .py files and definitely make the error message more clear 😅 

Thanks for this handy tool and definitely improves on my print() statements, especially the decorator to quickly check function performance when changing from one version to another in API calls 😄

**Comment by salabim** [comment]
Yes, I will make the error more clear and add somewhere that you can't use ycecream from a REPL.
Thanks for pointing out this behaviour (bug?).
You are on PythonistaCafé, aren't you. I want to do a little demo of ycecream tomorrow during the meetup. If you feel like it, please join (details on the forum).

**Comment by fdeswardt** [comment]
Thanks Ruud and yup, on PythonistaCafé and will do my best to join meetup today. Would be good if you could record the ycecream demo part of the meetup for replay later 🤗
