### ISSUE TITLE
f-string handling seem broken

### ISSUE THREAD

**Issue by Xaelias** [salabim/ycecream#13]
Hi,

Just looking around, considering using this package for my own stuff.
And while tryin out snippets, I found that f-strings didn't seem to behave the way the README suggests.

Namely (from the readme):
```
from ycecream import y

x = 12.3
y(f"{x:0.3e}")
y.values_only_for_fstrings = True
y(f"{x:0.3e}")
```

Spits out:
```
❯ python /tmp/t.py
y| f": '1.230e+01'
y| f": '1.230e+01'
```

This is using:
```
❯ python --version
Python 3.12.6
❯ uv pip freeze | grep -i ycecream
ycecream==1.3.17
```

Thanks!

**Comment by salabim** [comment]
Thanks for reporting this issue.
I have just fixed it. And ycecream is now even compatible with Python 3.13.
