### ISSUE TITLE
Enhancement: Add support for REPL sessions

### ISSUE THREAD

**Issue by PFython** [salabim/ycecream#4]

**Comment by salabim** [comment]
I don;t think this will be possible, at least not in a useful way. I could maybe make an implementation where the left-hand side of a 'pair' is left out, but what's the point of that? Then you can just use `print()`.
But I'm open to better solutions, of course.

**Comment by salabim** [comment]
Inspired by @PFython 's remarks, I have made ycecream compatible with REPLs, be it with extremely limited functionality:
* all arguments are just presented as such, i.e. no left-hand side, e.g.
  ```
   >>> hello = "world"
  >>> y(hello, hello * 2)
  y| 'hello', 'hellohello'
  ('hello', 'hellohello')
  ```
* line numbers are never shown  
* use as a decorator is not supported
* use as a context manager is not supported
