### ISSUE TITLE
Feature request: Hard line length limit

### ISSUE THREAD

**Issue by jkyeung** [salabim/ycecream#8]
This is probably a weird request, because it's motivated by running on a weird platform:

Can we have a setting which very strictly enforces the line length limit? So, even if the value being printed is a single string and doesn't have any natural breaking/wrapping point, if it's too long to fit, then just truncate it or wrap it anyway?

**Comment by salabim** [comment]
Interesting request. I'm thinking of adding a *enforce_line_length* attribute, that when True will truncate all output lines to the current  *line_length*.
Stay tuned.

**Comment by salabim** [comment]
Implemented. See readme.md or changelog.txt

**Comment by jkyeung** [comment]
Excellent! Thank you!
